# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Repo Action 페이지에 나타날 이름 
name: Spring Boot & Gradle CI/CD

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build -x test
   

    # 파일 압축
      - name: Make zip file
        run: |
          pwd
          ls -la
          zip RoutineProject.zip -r ./*
          mkdir -p deploy
          mv RoutineProject.zip deploy/RoutineProject.zip

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_REGION : ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_PW }}
        run: |
          pwd
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private ./RoutineProject.zip s3://routineprojectbucket
      
      - name: Code Deploy
        env:
          AWS_REGION : ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_PW }}
        run: |
          aws deploy create-deployment \
            --application-name RoutineProjectMaster \
            --deployment-group-name routine-deploy-group \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=routineprojectbucket,bundleType=zip,key=RoutineProject.zip \
            --region ap-northeast-2
